### PR TITLE
Add support for a Timestamper backed by Redis that is appropriate for multi VM environments.

### PR DESCRIPTION
**Pull request by bostanio**

### CODE REVIEW

**Comment by bostanio** [comment]
Any news on getting this included?

**Comment by johnou** [comment]
@debop still alive?

**Comment by johnou** [comment]
@bostanio couldn't help but notice your internal branch over at https://github.com/Nanigans/hibernate-redis/commits/internal_release . Are you still using it in production, have you run into any problems?

**Comment by bostanio** [comment]
We are using the branch in production. It contains this fix and a few other fixes that are also pull requests here.  We haven't spent a huge amount of time stress testing these features at great scale but they seem to work. I've tried to get action on this and other pull requests but @debop seems unresponsive despite looking like working on other repos. Tempted to fork this entire thing and just start publishing new versions.

**Comment by johnou** [comment]
@bostanio interested in forking it together? (wow that came out wrong, co-maintainers of course).

**Comment by bostanio** [comment]
Ha ha.

Yup definitely. Part of the reason I haven't done it is that I am not 100% up to speed on the requirements and mechanics of doing so. I'm comfortable in the code and forking on Github is easy but the details of publishing to maven repos etc. etc. is a bit unfamiliar.

There is also likely a need sometime soon to make this Hibernate 5 compatible and also add support for Redis Cluster. It would be good to have a more maintainable home for that work.

**Comment by johnou** [comment]
sgtm, I can take care of the CI and Maven side. What's the best way to reach / communicate with you to move this forward?

**Comment by bostanio** [comment]
work email is visible here: https://github.com/Nanigans/single-table-inheritance/blob/master/composer.json

trying to avoid the places where I paste that. Lets start there and see where we get.

**Comment by johnou** [comment]
@bostanio interested in taking this on (Timestamper with Reddison)? Closing pull request as the library no longer uses Redis.

**Comment by bostanio** [comment]
Its pretty important for multi node hibernate deployments to have distributed Timestamper support. I will take a look at what it takes to cut over to Redisson.

**Pull request closed without merging**
